Repository pnp/pnpcore, pull requests merged in 2024-05, with the labels that each got.

#1466 [docs] update authentication steps to new entra name
  docs/using-the-sdk/configuring authentication.md
Labels: area: documentation 📖

#1463 check response end by ending signal
  src/sdk/PnP.Core/Services/Core/BatchClient.cs
Labels: area: framework ⚙

#1464 allow access to the SPRequest Guid in a BacthRequest
  src/sdk/PnP.Core/Services/Core/BatchRequest.cs
Labels: area: framework ⚙

#1468 Added specialization support when adding a Team to a group
  src/sdk/PnP.Core.Admin/Model/Teams/Internal/TeamCreator.cs
  src/sdk/PnP.Core.Admin/Model/Teams/Public/Options/TeamOptions.cs
Labels: area: model 📐

#1467 #1461 Add better support for the Visibility HiddenMembership and added additionaldata support for creating a Group
  src/sdk/PnP.Core.Admin.Test/SharePoint/SiteCreationTests.cs
  src/sdk/PnP.Core.Admin.Test/SharePoint/SiteManagerTests.cs
  src/sdk/PnP.Core.Admin/Model/Microsoft365/Public/Options/GraphGroupOptions.cs
  src/sdk/PnP.Core.Admin/Model/SharePoint/Core/Internal/SiteCollectionCreator.cs
  src/sdk/PnP.Core.Admin/Model/SharePoint/Core/Public/Options/CommonGroupSiteOptions.cs
  src/sdk/PnP.Core/Model/Security/Public/Enums/GroupVisibility.cs
  src/sdk/PnP.Core/Model/Teams/Public/Enums/TeamVisibility.cs
Labels: area: model 📐
